/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthProfileRouteImport } from './routes/_auth.profile'
import { Route as AuthGuideRouteImport } from './routes/_auth.guide'
import { Route as AuthExportRouteImport } from './routes/_auth.export'
import { Route as AuthDataEntriesRouteImport } from './routes/_auth.dataEntries'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthDataEntryYearRouteImport } from './routes/_auth.dataEntry.$year'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGuideRoute = AuthGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthRoute,
} as any)
const AuthExportRoute = AuthExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDataEntriesRoute = AuthDataEntriesRouteImport.update({
  id: '/dataEntries',
  path: '/dataEntries',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDataEntryYearRoute = AuthDataEntryYearRouteImport.update({
  id: '/dataEntry/$year',
  path: '/dataEntry/$year',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthDashboardRoute
  '/dataEntries': typeof AuthDataEntriesRoute
  '/export': typeof AuthExportRoute
  '/guide': typeof AuthGuideRoute
  '/profile': typeof AuthProfileRoute
  '/dataEntry/$year': typeof AuthDataEntryYearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthDashboardRoute
  '/dataEntries': typeof AuthDataEntriesRoute
  '/export': typeof AuthExportRoute
  '/guide': typeof AuthGuideRoute
  '/profile': typeof AuthProfileRoute
  '/dataEntry/$year': typeof AuthDataEntryYearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/dataEntries': typeof AuthDataEntriesRoute
  '/_auth/export': typeof AuthExportRoute
  '/_auth/guide': typeof AuthGuideRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/dataEntry/$year': typeof AuthDataEntryYearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dataEntries'
    | '/export'
    | '/guide'
    | '/profile'
    | '/dataEntry/$year'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dataEntries'
    | '/export'
    | '/guide'
    | '/profile'
    | '/dataEntry/$year'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/dashboard'
    | '/_auth/dataEntries'
    | '/_auth/export'
    | '/_auth/guide'
    | '/_auth/profile'
    | '/_auth/dataEntry/$year'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/guide': {
      id: '/_auth/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthGuideRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/export': {
      id: '/_auth/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthExportRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dataEntries': {
      id: '/_auth/dataEntries'
      path: '/dataEntries'
      fullPath: '/dataEntries'
      preLoaderRoute: typeof AuthDataEntriesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dataEntry/$year': {
      id: '/_auth/dataEntry/$year'
      path: '/dataEntry/$year'
      fullPath: '/dataEntry/$year'
      preLoaderRoute: typeof AuthDataEntryYearRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthDataEntriesRoute: typeof AuthDataEntriesRoute
  AuthExportRoute: typeof AuthExportRoute
  AuthGuideRoute: typeof AuthGuideRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthDataEntryYearRoute: typeof AuthDataEntryYearRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthDataEntriesRoute: AuthDataEntriesRoute,
  AuthExportRoute: AuthExportRoute,
  AuthGuideRoute: AuthGuideRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthDataEntryYearRoute: AuthDataEntryYearRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
